FROM ecomtechoss/pisc:v0.18.2

ENV GRYPE_DB_CACHE_DIR=/opt/db/grype \
  GRYPE_DB_AUTO_UPDATE=false \
  TRIVY_CACHE_DIR=/opt/db/trivy

WORKDIR /home/nonroot

RUN mkdir /opt/db && \
  curl -sSL "https://pub-4c1eae2a180542b19ea7c88f1e4ccf07.r2.dev/inthewild.db" -o /opt/db/inthewild.db

RUN TODAY=$(date -u +%F) \
  && YESTERDAY=$(date -u -d "-1 day" +%F) \
  && if curl -sSL --fail "https://epss.empiricalsecurity.com/epss_scores-${TODAY}.csv.gz" -o /tmp/epss.csv.gz; then \
  echo "Downloaded EPSS for ${TODAY}"; \
  else \
  curl -sSL --fail "https://epss.empiricalsecurity.com/epss_scores-${YESTERDAY}.csv.gz" -o /tmp/epss.csv.gz && \
  echo "Downloaded EPSS for ${YESTERDAY}"; \
  fi \
  && zcat /tmp/epss.csv.gz > /opt/db/epss.csv \
  && rm /tmp/epss.csv.gz

RUN mkdir -p ${GRYPE_DB_CACHE_DIR} ${TRIVY_CACHE_DIR} \
  && grype db update \
  && trivy --cache-dir ${TRIVY_CACHE_DIR} image --download-db-only \
  && chown -R 65532:65532 /opt/db
